#!/bin/bash

set -u
set -e

if [[ `id -u` != "0" ]]; then
	echo >&2 "This script should be run as root!"
fi

fail()
{
	echo >&2 "Test $1: fail"
	exit 1
}

pass()
{
	echo >&2 "Test $1: pass"
}


#Test 1: If run with no arguments, frelink should exit normally
test1()
{
	if ! ./frelink; then
		fail 1
	else
		pass 1
	fi
}

# Test 2: The module should be able to be insmodded/rmmoded
#         with no ill effects. (look at dmesg)
test2()
{
	if ! insmod frelink.ko; then
		fail 2
	fi
	if ! rmmod frelink.ko; then
		fail 2
	else
		pass 2 
	fi
}


# Actually run the tests (easy to activate / deactivate)
test1
test2
